# fingerprints.py

FINGERPRINTS: dict[str, list[str]] = {
    "s3.amazonaws.com":           ["NoSuchBucket", "The specified bucket does not exist"],
    "cloudfront.amazonaws.com":   ["NoSuchBucket", "InvalidBucketName", "Bad Request", "ERROR: The request could not be satisfied"],
    "elasticbeanstalk.com":       ["404 Not Found"],
    "googlehosted.com":           ["The requested URL / was not found on this server", "Not Found"],
    "c.storage.googleapis.com":   ["NoSuchBucket", "The specified bucket does not exist"],
    "github.io":                  ["There isn't a GitHub Pages site here", "There is no GitHub Pages site"],
    "herokuapp.com":              ["No such app", "Application Error", "no-such-app"],
    "azurewebsites.net":          ["404 Web Site not found", "Resource not found"],
    "cloudapp.azure.com":         ["404 Web Site not found"],
    "azure-api.net":              ["Resource not found"],
    "azureedge.net":              ["<h2>Our services aren't available right now</h2>", "400 - Bad Request"],
    "trafficmanager.net":         ["404 Not Found"],
    "blob.core.windows.net":      ["BlobNotFound", "The specified blob does not exist"],
    "myshopify.com":              ["Sorry, this shop is currently unavailable", "Only one step left"],
    "tumblr.com":                 ["Whatever you were looking for doesn't currently exist", "There's nothing here"],
    "wordpress.com":              ["Do you want to register"],
    "bitbucket.io":               ["Repository not found"],
    "ghost.io":                   ["The thing you were looking for is no longer here", "Ghost: The Professional Publishing Platform"],
    "vercel.app":                 ["DEPLOYMENT_NOT_FOUND", "Project not found"],
    "netlify.app":                ["Page Not Found", "Site not found", "Not Found - Request ID"],
    "netlify.com":                ["Page Not Found", "Site not found"],
    "pantheonsite.io":            ["404 error unknown site", "The gods are wise"],
    "zendesk.com":                ["Help Center Closed", "Oops, this help center"],
    "helpjuice.com":              ["We could not find what you're looking for"],
    "helpscoutdocs.com":          ["No settings were found for this company"],
    "statuspage.io":              ["You are being redirected", "Status page"],
    "freshdesk.com":              ["May not be configured"],
    "uservoice.com":              ["This UserVoice subdomain is currently available"],
    "surge.sh":                   ["project not found"],
    "bitbucket.org":              ["Repository not found"],
    "smartling.com":              ["Domain is not configured"],
    "acquia-test.co":             ["Web Site Not Found"],
    "proposify.biz":              ["If you need immediate assistance"],
    "simplebooklet.com":          ["We can't find this SimpleBooklet"],
    "getresponse.com":            ["With GetResponse"],
    "vend.com":                   ["Oops, this page doesn't exist"],
    "aftership.app":              ["Oops.</h2>", "The page you're looking for"],
    "aha.io":                     ["There is no portal here"],
    "tictail.com":                ["to target URL", "Starting URL"],
    "brightcove.com":             ["<p class=\"bc-gallery-error-code\">"],
    "bigcartel.com":              ["<h1>Oops! We couldn&#8217;t find that page.</h1>"],
    "campaignmonitor.com":        ["Double check the URL", "Trying to access your account?"],
    "cargocollective.com":        ["404 Not Found"],
    "feedpress.me":               ["The feed has not been found."],
    "flexport.com":               ["You've reached a dead end"],
    "frontify.com":               ["404 - Page not found"],
    "gemfury.com":                ["404: This page could not be found"],
    "intercom.help":              ["Uh oh. That page doesn't exist"],
    "landingi.com":               ["It looks like you're lost"],
    "mashery.com":                ["Unrecognized domain"],
    "ngrok.io":                   ["ngrok.io not found", "Tunnel not found"],
    "pingdom.com":                ["Public Report Not Activated", "Sorry, couldn't find the status page"],
    "readme.io":                  ["Project doesnt exist"],
    "smugmug.com":                ["Page Not Found"],
    "strikingly.com":             ["But if you're looking to build your own website"],
    "teamwork.com":               ["Oops - We didn't find your site"],
    "thinkific.com":              ["You may have mistyped the address"],
    "tilda.ws":                   ["Domain has been assigned"],
    "uberflip.com":               ["Non-hub polygon  (404)"],
    "unbounce.com":               ["The requested URL was not found on this server"],
    "uptimerobot.com":            ["page not found"],
    "webflow.io":                 ["The page you are looking for doesn't exist", "Page not found"],
    "wishpond.com":               ["https://www.wishpond.com/404"],
    "worksites.net":              ["Hello! Sorry, but the website"],
    "wufoo.com":                  ["Hmmm....this", "looks like you've stumbled"],
}