# providers.py

PROVIDER_MAP: dict[str, str] = {
    "s3.amazonaws.com":           "AWS S3",
    "cloudfront.amazonaws.com":   "AWS CloudFront",
    "elasticbeanstalk.com":       "AWS Elastic Beanstalk",
    "googlehosted.com":           "GCP Cloud Storage",
    "c.storage.googleapis.com":   "GCP Cloud Storage",
    "azurewebsites.net":          "Azure App Service",
    "cloudapp.azure.com":         "Azure Cloud App",
    "azure-api.net":              "Azure API Management",
    "azureedge.net":              "Azure CDN",
    "trafficmanager.net":         "Azure Traffic Manager",
    "blob.core.windows.net":      "Azure Blob Storage",
    "github.io":                  "GitHub Pages",
    "herokuapp.com":              "Heroku",
    "myshopify.com":              "Shopify",
    "netlify.app":                "Netlify",
    "netlify.com":                "Netlify",
    "vercel.app":                 "Vercel",
    "ghost.io":                   "Ghost Pro",
    "bitbucket.io":               "Bitbucket",
    "bitbucket.org":              "Bitbucket",
    "wordpress.com":              "WordPress.com",
    "tumblr.com":                 "Tumblr",
    "pantheonsite.io":            "Pantheon",
    "zendesk.com":                "Zendesk",
    "helpjuice.com":              "Helpjuice",
    "helpscoutdocs.com":          "HelpScout",
    "statuspage.io":              "Atlassian Statuspage",
    "freshdesk.com":              "Freshdesk",
    "uservoice.com":              "UserVoice",
    "surge.sh":                   "Surge.sh",
    "smartling.com":              "Smartling",
    "acquia-test.co":             "Acquia",
    "proposify.biz":              "Proposify",
    "simplebooklet.com":          "SimpleBooklet",
    "getresponse.com":            "GetResponse",
    "vend.com":                   "Vend",
    "aftership.app":              "AfterShip",
    "aha.io":                     "Aha!",
    "tictail.com":                "Tictail",
    "brightcove.com":             "Brightcove",
    "bigcartel.com":              "Big Cartel",
    "campaignmonitor.com":        "Campaign Monitor",
    "cargocollective.com":        "Cargo Collective",
    "feedpress.me":               "FeedPress",
    "frontify.com":               "Frontify",
    "gemfury.com":                "Gemfury",
    "intercom.help":              "Intercom",
    "landingi.com":               "Landingi",
    "mashery.com":                "Mashery (TIBCO)",
    "ngrok.io":                   "ngrok",
    "pingdom.com":                "Pingdom",
    "readme.io":                  "ReadMe",
    "smugmug.com":                "SmugMug",
    "strikingly.com":             "Strikingly",
    "teamwork.com":               "Teamwork",
    "thinkific.com":              "Thinkific",
    "tilda.ws":                   "Tilda",
    "uberflip.com":               "Uberflip",
    "unbounce.com":               "Unbounce",
    "uptimerobot.com":            "UptimeRobot",
    "webflow.io":                 "Webflow",
    "wishpond.com":               "Wishpond",
    "worksites.net":              "Worksites",
    "wufoo.com":                  "Wufoo",
    "flexport.com":               "Flexport",
}